[tool.briefcase]
project_name = "mm"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/mm"
license = "BSD license"
author = 'Veer Singh'
author_email = "obiwan@veersingh.ca"

[tool.briefcase.app.mm]
formal_name = "mm"
description = "hackathon project"
icon = "src/mm/resources/mm"
sources = ['src/mm']
requires = ['tinydb']


[tool.briefcase.app.mm.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.mm.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.mm.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.mm.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.mm.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
